language: python
sudo: false
dist: bionic  # 18.04
if: (type = push AND branch IN (master)) OR (type = pull_request)
python:
  - 2.7
  - 3.7
  - pypy3
cache: pip
install:
  - pip install -e .
  - pip install -r requirements/test.txt
script: py.test --cov=unihan_db
after_success:
  - bash <(curl -s https://codecov.io/bash)
